// Code generated by mockery v2.43.2. DO NOT EDIT.

package usage

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"

	model "github.com/raito-io/cli-plugin-aws-account/aws/model"
)

// MockdataUsageRepository is an autogenerated mock type for the dataUsageRepository type
type MockdataUsageRepository struct {
	mock.Mock
}

type MockdataUsageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockdataUsageRepository) EXPECT() *MockdataUsageRepository_Expecter {
	return &MockdataUsageRepository_Expecter{mock: &_m.Mock}
}

// GetFile provides a mock function with given fields: ctx, bucket, key, region
func (_m *MockdataUsageRepository) GetFile(ctx context.Context, bucket string, key string, region *string) (io.ReadCloser, error) {
	ret := _m.Called(ctx, bucket, key, region)

	if len(ret) == 0 {
		panic("no return value specified for GetFile")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *string) (io.ReadCloser, error)); ok {
		return rf(ctx, bucket, key, region)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *string) io.ReadCloser); ok {
		r0 = rf(ctx, bucket, key, region)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *string) error); ok {
		r1 = rf(ctx, bucket, key, region)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockdataUsageRepository_GetFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFile'
type MockdataUsageRepository_GetFile_Call struct {
	*mock.Call
}

// GetFile is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - key string
//   - region *string
func (_e *MockdataUsageRepository_Expecter) GetFile(ctx interface{}, bucket interface{}, key interface{}, region interface{}) *MockdataUsageRepository_GetFile_Call {
	return &MockdataUsageRepository_GetFile_Call{Call: _e.mock.On("GetFile", ctx, bucket, key, region)}
}

func (_c *MockdataUsageRepository_GetFile_Call) Run(run func(ctx context.Context, bucket string, key string, region *string)) *MockdataUsageRepository_GetFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*string))
	})
	return _c
}

func (_c *MockdataUsageRepository_GetFile_Call) Return(_a0 io.ReadCloser, _a1 error) *MockdataUsageRepository_GetFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockdataUsageRepository_GetFile_Call) RunAndReturn(run func(context.Context, string, string, *string) (io.ReadCloser, error)) *MockdataUsageRepository_GetFile_Call {
	_c.Call.Return(run)
	return _c
}

// ListFiles provides a mock function with given fields: ctx, bucket, prefix
func (_m *MockdataUsageRepository) ListFiles(ctx context.Context, bucket string, prefix *string) ([]model.AwsS3Entity, string, error) {
	ret := _m.Called(ctx, bucket, prefix)

	if len(ret) == 0 {
		panic("no return value specified for ListFiles")
	}

	var r0 []model.AwsS3Entity
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string) ([]model.AwsS3Entity, string, error)); ok {
		return rf(ctx, bucket, prefix)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *string) []model.AwsS3Entity); ok {
		r0 = rf(ctx, bucket, prefix)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.AwsS3Entity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *string) string); ok {
		r1 = rf(ctx, bucket, prefix)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, *string) error); ok {
		r2 = rf(ctx, bucket, prefix)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockdataUsageRepository_ListFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFiles'
type MockdataUsageRepository_ListFiles_Call struct {
	*mock.Call
}

// ListFiles is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - prefix *string
func (_e *MockdataUsageRepository_Expecter) ListFiles(ctx interface{}, bucket interface{}, prefix interface{}) *MockdataUsageRepository_ListFiles_Call {
	return &MockdataUsageRepository_ListFiles_Call{Call: _e.mock.On("ListFiles", ctx, bucket, prefix)}
}

func (_c *MockdataUsageRepository_ListFiles_Call) Run(run func(ctx context.Context, bucket string, prefix *string)) *MockdataUsageRepository_ListFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*string))
	})
	return _c
}

func (_c *MockdataUsageRepository_ListFiles_Call) Return(_a0 []model.AwsS3Entity, _a1 string, _a2 error) *MockdataUsageRepository_ListFiles_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockdataUsageRepository_ListFiles_Call) RunAndReturn(run func(context.Context, string, *string) ([]model.AwsS3Entity, string, error)) *MockdataUsageRepository_ListFiles_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockdataUsageRepository creates a new instance of MockdataUsageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockdataUsageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockdataUsageRepository {
	mock := &MockdataUsageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
