// Code generated by mockery v2.50.0. DO NOT EDIT.

package data_access

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/raito-io/cli-plugin-aws-account/aws/model"
)

// MockdataAccessS3Repo is an autogenerated mock type for the dataAccessS3Repo type
type MockdataAccessS3Repo struct {
	mock.Mock
}

type MockdataAccessS3Repo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockdataAccessS3Repo) EXPECT() *MockdataAccessS3Repo_Expecter {
	return &MockdataAccessS3Repo_Expecter{mock: &_m.Mock}
}

// ListBuckets provides a mock function with given fields: ctx
func (_m *MockdataAccessS3Repo) ListBuckets(ctx context.Context) ([]model.AwsS3Entity, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListBuckets")
	}

	var r0 []model.AwsS3Entity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.AwsS3Entity, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.AwsS3Entity); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.AwsS3Entity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockdataAccessS3Repo_ListBuckets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBuckets'
type MockdataAccessS3Repo_ListBuckets_Call struct {
	*mock.Call
}

// ListBuckets is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockdataAccessS3Repo_Expecter) ListBuckets(ctx interface{}) *MockdataAccessS3Repo_ListBuckets_Call {
	return &MockdataAccessS3Repo_ListBuckets_Call{Call: _e.mock.On("ListBuckets", ctx)}
}

func (_c *MockdataAccessS3Repo_ListBuckets_Call) Run(run func(ctx context.Context)) *MockdataAccessS3Repo_ListBuckets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockdataAccessS3Repo_ListBuckets_Call) Return(_a0 []model.AwsS3Entity, _a1 error) *MockdataAccessS3Repo_ListBuckets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockdataAccessS3Repo_ListBuckets_Call) RunAndReturn(run func(context.Context) ([]model.AwsS3Entity, error)) *MockdataAccessS3Repo_ListBuckets_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockdataAccessS3Repo creates a new instance of MockdataAccessS3Repo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockdataAccessS3Repo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockdataAccessS3Repo {
	mock := &MockdataAccessS3Repo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
