// Code generated by mockery v2.50.0. DO NOT EDIT.

package data_access

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/raito-io/cli-plugin-aws-account/aws/model"
)

// MockdataAccessIamRepository is an autogenerated mock type for the dataAccessIamRepository type
type MockdataAccessIamRepository struct {
	mock.Mock
}

type MockdataAccessIamRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockdataAccessIamRepository) EXPECT() *MockdataAccessIamRepository_Expecter {
	return &MockdataAccessIamRepository_Expecter{mock: &_m.Mock}
}

// GetGroups provides a mock function with given fields: ctx
func (_m *MockdataAccessIamRepository) GetGroups(ctx context.Context) ([]model.GroupEntity, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetGroups")
	}

	var r0 []model.GroupEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.GroupEntity, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.GroupEntity); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.GroupEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockdataAccessIamRepository_GetGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroups'
type MockdataAccessIamRepository_GetGroups_Call struct {
	*mock.Call
}

// GetGroups is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockdataAccessIamRepository_Expecter) GetGroups(ctx interface{}) *MockdataAccessIamRepository_GetGroups_Call {
	return &MockdataAccessIamRepository_GetGroups_Call{Call: _e.mock.On("GetGroups", ctx)}
}

func (_c *MockdataAccessIamRepository_GetGroups_Call) Run(run func(ctx context.Context)) *MockdataAccessIamRepository_GetGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockdataAccessIamRepository_GetGroups_Call) Return(_a0 []model.GroupEntity, _a1 error) *MockdataAccessIamRepository_GetGroups_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockdataAccessIamRepository_GetGroups_Call) RunAndReturn(run func(context.Context) ([]model.GroupEntity, error)) *MockdataAccessIamRepository_GetGroups_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function with given fields: ctx, withDetails
func (_m *MockdataAccessIamRepository) GetUsers(ctx context.Context, withDetails bool) ([]model.UserEntity, error) {
	ret := _m.Called(ctx, withDetails)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []model.UserEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bool) ([]model.UserEntity, error)); ok {
		return rf(ctx, withDetails)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bool) []model.UserEntity); ok {
		r0 = rf(ctx, withDetails)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.UserEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bool) error); ok {
		r1 = rf(ctx, withDetails)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockdataAccessIamRepository_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type MockdataAccessIamRepository_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - withDetails bool
func (_e *MockdataAccessIamRepository_Expecter) GetUsers(ctx interface{}, withDetails interface{}) *MockdataAccessIamRepository_GetUsers_Call {
	return &MockdataAccessIamRepository_GetUsers_Call{Call: _e.mock.On("GetUsers", ctx, withDetails)}
}

func (_c *MockdataAccessIamRepository_GetUsers_Call) Run(run func(ctx context.Context, withDetails bool)) *MockdataAccessIamRepository_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bool))
	})
	return _c
}

func (_c *MockdataAccessIamRepository_GetUsers_Call) Return(_a0 []model.UserEntity, _a1 error) *MockdataAccessIamRepository_GetUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockdataAccessIamRepository_GetUsers_Call) RunAndReturn(run func(context.Context, bool) ([]model.UserEntity, error)) *MockdataAccessIamRepository_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockdataAccessIamRepository creates a new instance of MockdataAccessIamRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockdataAccessIamRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockdataAccessIamRepository {
	mock := &MockdataAccessIamRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
