name: Raito CLI - AWS Account Plugin - Build
on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  GOPRIVATE: "github.com/raito-io/*"

permissions:
  id-token: write
  contents: read

jobs:
  setup-infra:
    uses: ./.github/workflows/generate-infra.yml
    with:
      targetEnvironment: integration_testing
      demo-infra: false
      testing-infra: true
    secrets: inherit

  build:
    environment: integration_testing
    runs-on: ubuntu-latest

    needs:
      - setup-infra

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true

      - name: Configure git for private modules
        run: git config --global url."https://${{secrets.CI_SECRETS_TOKEN_USER}}:${{secrets.CI_SECRETS_TOKEN}}@github.com".insteadOf "https://github.com"

      - name: Mod Tidy
        run: go mod tidy

      - name: Build
        run: make build

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.59.0

      - name: Test
        run: make test
        env:
          AWS_ACCOUNT: ${{ secrets.AWS_TEST_ACCOUNT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_TEST_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_TEST_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_TEST_REGION }}

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt
